variables:
  MASTER_EDGE_IMAGE: $CI_REGISTRY_IMAGE/validator:master
  RELEASE_EDGE_IMAGE: $CI_REGISTRY_IMAGE/validator:$CI_COMMIT_TAG

  DOCKER_DRIVER: overlay

services:
  - docker:stable-dind

stages:
  - build
# --------

build-operator-master:
  stage: build
  image: docker
  before_script:
    - apk update; apk add make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make -C src/
  only:
    - master
  after_script:
    - docker tag federated/validator $MASTER_EDGE_IMAGE
    - docker push $MASTER_EDGE_IMAGE

build-harmonia-edge-tag:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $MASTER_EDGE_IMAGE || true
    - docker tag $MASTER_EDGE_IMAGE $RELEASE_EDGE_IMAGE
    - docker push $RELEASE_EDGE_IMAGE
  only:
    - tags