variables:
  MASTER_EDGE_IMAGE: $CI_REGISTRY_IMAGE/validator:master

  DOCKER_DRIVER: overlay

services:
  - docker:stable-dind

stages:
  - build
# --------

build-operator-master:
  stage: build
  image: docker
  before_script:
    - apk update; apk add make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make -C src/
  only:
    - master
  after_script:
    - docker tag federated/validator $MASTER_EDGE_IMAGE
    - docker push $MASTER_EDGE_IMAGE