version: "2.3"
services:
  app:
    container_name: hello-fl
    image: registry.corp.ailabs.tw/federated-learning/hello-fl/edge:1.3.4
    environment:
      LOCAL_MODEL_PATH: /model/weight.ckpt
      GLOBAL_MODEL_PATH: /model/merge.ckpt
      NVIDIA_VISIBLE_DEVICES: 0
    runtime: nvidia
    volumes:
      - /var/model:/model
    ports:
      - 7878:7878
    ipc: host
    networks:
      - fl-network
    healthcheck:
      test: ["CMD","curl","-f","http://127.0.0.1:7878", "||", "exit" ,"1"]
      interval: 2m
      timeout: 10s
      retries: 3
  validator:
    container_name: federated-validator
    image: registry.corp.ailabs.tw/federated-learning/fl_app_validator/validator:master
    depends_on:
      - app
    environment:
      APP_URI: app:7878
      GRPC_VERBOSITY: DEBUG
      GRPC_TRACE: call_error,server_channel,http,http1,handshaker
    ports:
      - 9080:9080
    networks:
      - fl-network

networks:
  fl-network:
    external: false
    name: fl-network
