// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.2
// source: service.proto

package protos

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LocalTrainResult_Error int32

const (
	LocalTrainResult_SUCCESS LocalTrainResult_Error = 0
	LocalTrainResult_FAIL    LocalTrainResult_Error = 1
)

// Enum value maps for LocalTrainResult_Error.
var (
	LocalTrainResult_Error_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
	}
	LocalTrainResult_Error_value = map[string]int32{
		"SUCCESS": 0,
		"FAIL":    1,
	}
)

func (x LocalTrainResult_Error) Enum() *LocalTrainResult_Error {
	p := new(LocalTrainResult_Error)
	*p = x
	return p
}

func (x LocalTrainResult_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalTrainResult_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (LocalTrainResult_Error) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x LocalTrainResult_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalTrainResult_Error.Descriptor instead.
func (LocalTrainResult_Error) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5, 0}
}

type AggregateResult_Error int32

const (
	AggregateResult_SUCCESS             AggregateResult_Error = 0
	AggregateResult_AGGREGATE_CONDITION AggregateResult_Error = 1 // FUTURE: Cannot aggregate due to aggregation policy
	AggregateResult_FAIL                AggregateResult_Error = 2
)

// Enum value maps for AggregateResult_Error.
var (
	AggregateResult_Error_name = map[int32]string{
		0: "SUCCESS",
		1: "AGGREGATE_CONDITION",
		2: "FAIL",
	}
	AggregateResult_Error_value = map[string]int32{
		"SUCCESS":             0,
		"AGGREGATE_CONDITION": 1,
		"FAIL":                2,
	}
)

func (x AggregateResult_Error) Enum() *AggregateResult_Error {
	p := new(AggregateResult_Error)
	*p = x
	return p
}

func (x AggregateResult_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregateResult_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (AggregateResult_Error) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x AggregateResult_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregateResult_Error.Descriptor instead.
func (AggregateResult_Error) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level   string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatasetSize int32   `protobuf:"varint,1,opt,name=datasetSize,proto3" json:"datasetSize,omitempty"`
	Epoch       int32   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Importance  float64 `protobuf:"fixed64,3,opt,name=importance,proto3" json:"importance,omitempty"`
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *MetaData) GetDatasetSize() int32 {
	if x != nil {
		return x.DatasetSize
	}
	return 0
}

func (x *MetaData) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *MetaData) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

type LocalTrainParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpR int32 `protobuf:"varint,1,opt,name=EpR,proto3" json:"EpR,omitempty"` // Epoch Per Round
}

func (x *LocalTrainParams) Reset() {
	*x = LocalTrainParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalTrainParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTrainParams) ProtoMessage() {}

func (x *LocalTrainParams) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTrainParams.ProtoReflect.Descriptor instead.
func (*LocalTrainParams) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *LocalTrainParams) GetEpR() int32 {
	if x != nil {
		return x.EpR
	}
	return 0
}

type AggregateParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalModels     []*AggregateParams_LocalModel    `protobuf:"bytes,10,rep,name=localModels,proto3" json:"localModels,omitempty"`
	AggregatedModel *AggregateParams_AggregatedModel `protobuf:"bytes,12,opt,name=aggregatedModel,proto3" json:"aggregatedModel,omitempty"`
}

func (x *AggregateParams) Reset() {
	*x = AggregateParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateParams) ProtoMessage() {}

func (x *AggregateParams) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateParams.ProtoReflect.Descriptor instead.
func (*AggregateParams) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *AggregateParams) GetLocalModels() []*AggregateParams_LocalModel {
	if x != nil {
		return x.LocalModels
	}
	return nil
}

func (x *AggregateParams) GetAggregatedModel() *AggregateParams_AggregatedModel {
	if x != nil {
		return x.AggregatedModel
	}
	return nil
}

type LocalTrainResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error    LocalTrainResult_Error `protobuf:"varint,13,opt,name=error,proto3,enum=protos.LocalTrainResult_Error" json:"error,omitempty"`
	Metadata *MetaData              `protobuf:"bytes,15,opt,name=metadata,proto3" json:"metadata,omitempty"` // FUTURE:
	Metrics  map[string]float64     `protobuf:"bytes,18,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
}

func (x *LocalTrainResult) Reset() {
	*x = LocalTrainResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalTrainResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTrainResult) ProtoMessage() {}

func (x *LocalTrainResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTrainResult.ProtoReflect.Descriptor instead.
func (*LocalTrainResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *LocalTrainResult) GetError() LocalTrainResult_Error {
	if x != nil {
		return x.Error
	}
	return LocalTrainResult_SUCCESS
}

func (x *LocalTrainResult) GetMetadata() *MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LocalTrainResult) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type AggregateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error    AggregateResult_Error `protobuf:"varint,16,opt,name=error,proto3,enum=protos.AggregateResult_Error" json:"error,omitempty"`
	Metadata *MetaData             `protobuf:"bytes,17,opt,name=metadata,proto3" json:"metadata,omitempty"` // FUTURE:
	Metrics  map[string]float64    `protobuf:"bytes,19,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
}

func (x *AggregateResult) Reset() {
	*x = AggregateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateResult) ProtoMessage() {}

func (x *AggregateResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateResult.ProtoReflect.Descriptor instead.
func (*AggregateResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *AggregateResult) GetError() AggregateResult_Error {
	if x != nil {
		return x.Error
	}
	return AggregateResult_SUCCESS
}

func (x *AggregateResult) GetMetadata() *MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AggregateResult) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type AggregateParams_LocalModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string             `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	DatasetSize int32              `protobuf:"varint,8,opt,name=datasetSize,proto3" json:"datasetSize,omitempty"`
	Metadata    *MetaData          `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"` // FUTURE:
	Metrics     map[string]float64 `protobuf:"bytes,21,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
}

func (x *AggregateParams_LocalModel) Reset() {
	*x = AggregateParams_LocalModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateParams_LocalModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateParams_LocalModel) ProtoMessage() {}

func (x *AggregateParams_LocalModel) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateParams_LocalModel.ProtoReflect.Descriptor instead.
func (*AggregateParams_LocalModel) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *AggregateParams_LocalModel) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AggregateParams_LocalModel) GetDatasetSize() int32 {
	if x != nil {
		return x.DatasetSize
	}
	return 0
}

func (x *AggregateParams_LocalModel) GetMetadata() *MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AggregateParams_LocalModel) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type AggregateParams_AggregatedModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,11,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *AggregateParams_AggregatedModel) Reset() {
	*x = AggregateParams_AggregatedModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateParams_AggregatedModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateParams_AggregatedModel) ProtoMessage() {}

func (x *AggregateParams_AggregatedModel) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateParams_AggregatedModel.ProtoReflect.Descriptor instead.
func (*AggregateParams_AggregatedModel) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4, 1}
}

func (x *AggregateParams_AggregatedModel) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x35, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x62, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65,
	0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x24, 0x0a, 0x10, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x45, 0x70, 0x52, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45, 0x70,
	0x52, 0x22, 0xcb, 0x03, 0x0a, 0x0f, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x44, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0b,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x51, 0x0a, 0x0f, 0x61,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x41, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0f, 0x61,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0xf7,
	0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x49, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x15, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x3a, 0x0a, 0x0c,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x25, 0x0a, 0x0f, 0x41, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x93, 0x02, 0x0a, 0x10, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3f, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x18, 0x12, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1e, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46,
	0x41, 0x49, 0x4c, 0x10, 0x01, 0x22, 0xa9, 0x02, 0x0a, 0x0f, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2c,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3e, 0x0a, 0x07,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x13, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x3a, 0x0a, 0x0c,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x37, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x17,
	0x0a, 0x13, 0x41, 0x47, 0x47, 0x52, 0x45, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x44,
	0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10,
	0x02, 0x32, 0x79, 0x0a, 0x0c, 0x45, 0x64, 0x67, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x3d, 0x0a, 0x10, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x2a, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x1a, 0x0d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x32, 0x80, 0x02, 0x0a,
	0x07, 0x45, 0x64, 0x67, 0x65, 0x41, 0x70, 0x70, 0x12, 0x2e, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x2b, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x0d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x30,
	0x0a, 0x0e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75, 0x70, 0x74,
	0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x2d, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x32,
	0x82, 0x01, 0x0a, 0x17, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x0f, 0x41,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x4c, 0x6f, 0x67, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x32, 0x7a, 0x0a, 0x12, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x70, 0x70, 0x12, 0x35, 0x0a, 0x09, 0x41, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x2d, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_service_proto_goTypes = []interface{}{
	(LocalTrainResult_Error)(0),             // 0: protos.LocalTrainResult.Error
	(AggregateResult_Error)(0),              // 1: protos.AggregateResult.Error
	(*Empty)(nil),                           // 2: protos.Empty
	(*Log)(nil),                             // 3: protos.Log
	(*MetaData)(nil),                        // 4: protos.MetaData
	(*LocalTrainParams)(nil),                // 5: protos.LocalTrainParams
	(*AggregateParams)(nil),                 // 6: protos.AggregateParams
	(*LocalTrainResult)(nil),                // 7: protos.LocalTrainResult
	(*AggregateResult)(nil),                 // 8: protos.AggregateResult
	(*AggregateParams_LocalModel)(nil),      // 9: protos.AggregateParams.LocalModel
	(*AggregateParams_AggregatedModel)(nil), // 10: protos.AggregateParams.AggregatedModel
	nil,                                     // 11: protos.AggregateParams.LocalModel.MetricsEntry
	nil,                                     // 12: protos.LocalTrainResult.MetricsEntry
	nil,                                     // 13: protos.AggregateResult.MetricsEntry
}
var file_service_proto_depIdxs = []int32{
	9,  // 0: protos.AggregateParams.localModels:type_name -> protos.AggregateParams.LocalModel
	10, // 1: protos.AggregateParams.aggregatedModel:type_name -> protos.AggregateParams.AggregatedModel
	0,  // 2: protos.LocalTrainResult.error:type_name -> protos.LocalTrainResult.Error
	4,  // 3: protos.LocalTrainResult.metadata:type_name -> protos.MetaData
	12, // 4: protos.LocalTrainResult.metrics:type_name -> protos.LocalTrainResult.MetricsEntry
	1,  // 5: protos.AggregateResult.error:type_name -> protos.AggregateResult.Error
	4,  // 6: protos.AggregateResult.metadata:type_name -> protos.MetaData
	13, // 7: protos.AggregateResult.metrics:type_name -> protos.AggregateResult.MetricsEntry
	4,  // 8: protos.AggregateParams.LocalModel.metadata:type_name -> protos.MetaData
	11, // 9: protos.AggregateParams.LocalModel.metrics:type_name -> protos.AggregateParams.LocalModel.MetricsEntry
	7,  // 10: protos.EdgeOperator.LocalTrainFinish:input_type -> protos.LocalTrainResult
	3,  // 11: protos.EdgeOperator.LogMessage:input_type -> protos.Log
	2,  // 12: protos.EdgeApp.DataValidate:input_type -> protos.Empty
	5,  // 13: protos.EdgeApp.LocalTrain:input_type -> protos.LocalTrainParams
	2,  // 14: protos.EdgeApp.TrainInit:input_type -> protos.Empty
	2,  // 15: protos.EdgeApp.TrainInterrupt:input_type -> protos.Empty
	2,  // 16: protos.EdgeApp.TrainFinish:input_type -> protos.Empty
	8,  // 17: protos.AggregateServerOperator.AggregateFinish:input_type -> protos.AggregateResult
	3,  // 18: protos.AggregateServerOperator.LogMessage:input_type -> protos.Log
	6,  // 19: protos.AggregateServerApp.Aggregate:input_type -> protos.AggregateParams
	2,  // 20: protos.AggregateServerApp.TrainFinish:input_type -> protos.Empty
	2,  // 21: protos.EdgeOperator.LocalTrainFinish:output_type -> protos.Empty
	2,  // 22: protos.EdgeOperator.LogMessage:output_type -> protos.Empty
	2,  // 23: protos.EdgeApp.DataValidate:output_type -> protos.Empty
	2,  // 24: protos.EdgeApp.LocalTrain:output_type -> protos.Empty
	2,  // 25: protos.EdgeApp.TrainInit:output_type -> protos.Empty
	2,  // 26: protos.EdgeApp.TrainInterrupt:output_type -> protos.Empty
	2,  // 27: protos.EdgeApp.TrainFinish:output_type -> protos.Empty
	2,  // 28: protos.AggregateServerOperator.AggregateFinish:output_type -> protos.Empty
	2,  // 29: protos.AggregateServerOperator.LogMessage:output_type -> protos.Empty
	2,  // 30: protos.AggregateServerApp.Aggregate:output_type -> protos.Empty
	2,  // 31: protos.AggregateServerApp.TrainFinish:output_type -> protos.Empty
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalTrainParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalTrainResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateParams_LocalModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateParams_AggregatedModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EdgeOperatorClient is the client API for EdgeOperator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EdgeOperatorClient interface {
	LocalTrainFinish(ctx context.Context, in *LocalTrainResult, opts ...grpc.CallOption) (*Empty, error)
	LogMessage(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Empty, error)
}

type edgeOperatorClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeOperatorClient(cc grpc.ClientConnInterface) EdgeOperatorClient {
	return &edgeOperatorClient{cc}
}

func (c *edgeOperatorClient) LocalTrainFinish(ctx context.Context, in *LocalTrainResult, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.EdgeOperator/LocalTrainFinish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeOperatorClient) LogMessage(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.EdgeOperator/LogMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeOperatorServer is the server API for EdgeOperator service.
type EdgeOperatorServer interface {
	LocalTrainFinish(context.Context, *LocalTrainResult) (*Empty, error)
	LogMessage(context.Context, *Log) (*Empty, error)
}

// UnimplementedEdgeOperatorServer can be embedded to have forward compatible implementations.
type UnimplementedEdgeOperatorServer struct {
}

func (*UnimplementedEdgeOperatorServer) LocalTrainFinish(context.Context, *LocalTrainResult) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalTrainFinish not implemented")
}
func (*UnimplementedEdgeOperatorServer) LogMessage(context.Context, *Log) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogMessage not implemented")
}

func RegisterEdgeOperatorServer(s *grpc.Server, srv EdgeOperatorServer) {
	s.RegisterService(&_EdgeOperator_serviceDesc, srv)
}

func _EdgeOperator_LocalTrainFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalTrainResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeOperatorServer).LocalTrainFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EdgeOperator/LocalTrainFinish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeOperatorServer).LocalTrainFinish(ctx, req.(*LocalTrainResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeOperator_LogMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeOperatorServer).LogMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EdgeOperator/LogMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeOperatorServer).LogMessage(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

var _EdgeOperator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.EdgeOperator",
	HandlerType: (*EdgeOperatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LocalTrainFinish",
			Handler:    _EdgeOperator_LocalTrainFinish_Handler,
		},
		{
			MethodName: "LogMessage",
			Handler:    _EdgeOperator_LogMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// EdgeAppClient is the client API for EdgeApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EdgeAppClient interface {
	DataValidate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	LocalTrain(ctx context.Context, in *LocalTrainParams, opts ...grpc.CallOption) (*Empty, error)
	TrainInit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	TrainInterrupt(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	TrainFinish(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type edgeAppClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeAppClient(cc grpc.ClientConnInterface) EdgeAppClient {
	return &edgeAppClient{cc}
}

func (c *edgeAppClient) DataValidate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.EdgeApp/DataValidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeAppClient) LocalTrain(ctx context.Context, in *LocalTrainParams, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.EdgeApp/LocalTrain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeAppClient) TrainInit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.EdgeApp/TrainInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeAppClient) TrainInterrupt(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.EdgeApp/TrainInterrupt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeAppClient) TrainFinish(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.EdgeApp/TrainFinish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeAppServer is the server API for EdgeApp service.
type EdgeAppServer interface {
	DataValidate(context.Context, *Empty) (*Empty, error)
	LocalTrain(context.Context, *LocalTrainParams) (*Empty, error)
	TrainInit(context.Context, *Empty) (*Empty, error)
	TrainInterrupt(context.Context, *Empty) (*Empty, error)
	TrainFinish(context.Context, *Empty) (*Empty, error)
}

// UnimplementedEdgeAppServer can be embedded to have forward compatible implementations.
type UnimplementedEdgeAppServer struct {
}

func (*UnimplementedEdgeAppServer) DataValidate(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataValidate not implemented")
}
func (*UnimplementedEdgeAppServer) LocalTrain(context.Context, *LocalTrainParams) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalTrain not implemented")
}
func (*UnimplementedEdgeAppServer) TrainInit(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainInit not implemented")
}
func (*UnimplementedEdgeAppServer) TrainInterrupt(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainInterrupt not implemented")
}
func (*UnimplementedEdgeAppServer) TrainFinish(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainFinish not implemented")
}

func RegisterEdgeAppServer(s *grpc.Server, srv EdgeAppServer) {
	s.RegisterService(&_EdgeApp_serviceDesc, srv)
}

func _EdgeApp_DataValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeAppServer).DataValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EdgeApp/DataValidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeAppServer).DataValidate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeApp_LocalTrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalTrainParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeAppServer).LocalTrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EdgeApp/LocalTrain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeAppServer).LocalTrain(ctx, req.(*LocalTrainParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeApp_TrainInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeAppServer).TrainInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EdgeApp/TrainInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeAppServer).TrainInit(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeApp_TrainInterrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeAppServer).TrainInterrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EdgeApp/TrainInterrupt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeAppServer).TrainInterrupt(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeApp_TrainFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeAppServer).TrainFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EdgeApp/TrainFinish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeAppServer).TrainFinish(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _EdgeApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.EdgeApp",
	HandlerType: (*EdgeAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataValidate",
			Handler:    _EdgeApp_DataValidate_Handler,
		},
		{
			MethodName: "LocalTrain",
			Handler:    _EdgeApp_LocalTrain_Handler,
		},
		{
			MethodName: "TrainInit",
			Handler:    _EdgeApp_TrainInit_Handler,
		},
		{
			MethodName: "TrainInterrupt",
			Handler:    _EdgeApp_TrainInterrupt_Handler,
		},
		{
			MethodName: "TrainFinish",
			Handler:    _EdgeApp_TrainFinish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// AggregateServerOperatorClient is the client API for AggregateServerOperator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AggregateServerOperatorClient interface {
	AggregateFinish(ctx context.Context, in *AggregateResult, opts ...grpc.CallOption) (*Empty, error)
	LogMessage(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Empty, error)
}

type aggregateServerOperatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregateServerOperatorClient(cc grpc.ClientConnInterface) AggregateServerOperatorClient {
	return &aggregateServerOperatorClient{cc}
}

func (c *aggregateServerOperatorClient) AggregateFinish(ctx context.Context, in *AggregateResult, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.AggregateServerOperator/AggregateFinish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregateServerOperatorClient) LogMessage(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.AggregateServerOperator/LogMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregateServerOperatorServer is the server API for AggregateServerOperator service.
type AggregateServerOperatorServer interface {
	AggregateFinish(context.Context, *AggregateResult) (*Empty, error)
	LogMessage(context.Context, *Log) (*Empty, error)
}

// UnimplementedAggregateServerOperatorServer can be embedded to have forward compatible implementations.
type UnimplementedAggregateServerOperatorServer struct {
}

func (*UnimplementedAggregateServerOperatorServer) AggregateFinish(context.Context, *AggregateResult) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateFinish not implemented")
}
func (*UnimplementedAggregateServerOperatorServer) LogMessage(context.Context, *Log) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogMessage not implemented")
}

func RegisterAggregateServerOperatorServer(s *grpc.Server, srv AggregateServerOperatorServer) {
	s.RegisterService(&_AggregateServerOperator_serviceDesc, srv)
}

func _AggregateServerOperator_AggregateFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateServerOperatorServer).AggregateFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AggregateServerOperator/AggregateFinish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateServerOperatorServer).AggregateFinish(ctx, req.(*AggregateResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregateServerOperator_LogMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateServerOperatorServer).LogMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AggregateServerOperator/LogMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateServerOperatorServer).LogMessage(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

var _AggregateServerOperator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.AggregateServerOperator",
	HandlerType: (*AggregateServerOperatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AggregateFinish",
			Handler:    _AggregateServerOperator_AggregateFinish_Handler,
		},
		{
			MethodName: "LogMessage",
			Handler:    _AggregateServerOperator_LogMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// AggregateServerAppClient is the client API for AggregateServerApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AggregateServerAppClient interface {
	Aggregate(ctx context.Context, in *AggregateParams, opts ...grpc.CallOption) (*Empty, error)
	TrainFinish(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type aggregateServerAppClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregateServerAppClient(cc grpc.ClientConnInterface) AggregateServerAppClient {
	return &aggregateServerAppClient{cc}
}

func (c *aggregateServerAppClient) Aggregate(ctx context.Context, in *AggregateParams, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.AggregateServerApp/Aggregate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregateServerAppClient) TrainFinish(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.AggregateServerApp/TrainFinish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregateServerAppServer is the server API for AggregateServerApp service.
type AggregateServerAppServer interface {
	Aggregate(context.Context, *AggregateParams) (*Empty, error)
	TrainFinish(context.Context, *Empty) (*Empty, error)
}

// UnimplementedAggregateServerAppServer can be embedded to have forward compatible implementations.
type UnimplementedAggregateServerAppServer struct {
}

func (*UnimplementedAggregateServerAppServer) Aggregate(context.Context, *AggregateParams) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Aggregate not implemented")
}
func (*UnimplementedAggregateServerAppServer) TrainFinish(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainFinish not implemented")
}

func RegisterAggregateServerAppServer(s *grpc.Server, srv AggregateServerAppServer) {
	s.RegisterService(&_AggregateServerApp_serviceDesc, srv)
}

func _AggregateServerApp_Aggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateServerAppServer).Aggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AggregateServerApp/Aggregate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateServerAppServer).Aggregate(ctx, req.(*AggregateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregateServerApp_TrainFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateServerAppServer).TrainFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AggregateServerApp/TrainFinish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateServerAppServer).TrainFinish(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AggregateServerApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.AggregateServerApp",
	HandlerType: (*AggregateServerAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Aggregate",
			Handler:    _AggregateServerApp_Aggregate_Handler,
		},
		{
			MethodName: "TrainFinish",
			Handler:    _AggregateServerApp_TrainFinish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
